language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fabioacd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fabioacd/docker-react npm run test -- --coverage
